---
title: 'Application Case 2: Endothelial cells'
output: html_notebook
---

### Loading Libraries
```{r message=FALSE, warning=FALSE}
library(rPanglaoDB)
library(Seurat)
library(harmony)
library(Nebulosa)
library(ggplot2)
library(ggrepel)
library(fgsea)
library(GSVA)
library(statsExpressions)
BIOP <- gmtPathways('https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=BioPlanet_2019')
```

```{r}
LEC <- getMarkers(include = c('PECAM1', 'PDPN', 'PROX1'))
```


```{r}
LEC <- getSamples(srs = unique(LEC$SRS), 
                  specie = 'Homo sapiens', 
                  celltype = 'Endothelial cells', 
                  include = c('PECAM1', 'PDPN', 'PROX1'))
```

```{r}
BEC <- getMarkers(include = c('PECAM1', 'VWF'), exclude = c('PDPN', 'ACTA2'))
```

```{r}
BEC <- getSamples(srs = unique(BEC$SRS),
                        specie = 'Homo sapiens',
                        celltype = 'Endothelial cells',
                        include = c('PECAM1', 'VWF'),
                        exclude = c('PDPN', 'ACTA2'))
```
```{r}
Endothelial <- merge(LEC, BEC)
```

```{r}
Endothelial <- NormalizeData(Endothelial)
Endothelial <- FindVariableFeatures(Endothelial)
Endothelial <- ScaleData(Endothelial)
Endothelial <- RunPCA(Endothelial)
Endothelial <- RunHarmony(Endothelial, group.by.vars = 'orig.ident')
Endothelial <- RunTSNE(Endothelial, reduction = 'harmony')
```
```{r}
TSNEPlot(Endothelial)
plot_density(Endothelial, features = c('PECAM1', 'PDPN', 'PROX1'))
```
