---
title: 'Application Case: Fibrocytes'
output:
  html_notebook: default
---

Loading Libraries
```{r message=FALSE, warning=FALSE}
library(rPanglaoDB)
library(Seurat)
library(harmony)
library(Nebulosa)
library(ggplot2)
library(ggrepel)
library(fgsea)
library(GSVA)
library(statsExpressions)
BIOP <- gmtPathways('https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=BioPlanet_2019')
```

```{r}
FibrocytesClusters <- getMarkers(
  include = c('ACTA2','CD34', 'COL5A1', 'COL5A2', 'COL5A3', 'FAP'), 
  exclude = 'CSF1R')

FibrocytesClusters
```
```{r}
FibrocytesCounts <- getSamples(tissue = 'Dermis', specie = 'Mus musculus', celltype = 'Fibroblasts')
```
```{r message=FALSE, warning=FALSE}
FibrocytesCounts <- NormalizeData(FibrocytesCounts, verbose = FALSE)
FibrocytesCounts <- ScaleData(FibrocytesCounts, verbose = FALSE)
FibrocytesCounts <- FindVariableFeatures(FibrocytesCounts, verbose = FALSE)
FibrocytesCounts <- RunPCA(FibrocytesCounts, verbose = FALSE)
FibrocytesCounts <- RunHarmony(FibrocytesCounts, 
                               group.by.vars = 'orig.ident', 
                               max.iter.harmony = 50, 
                               verbose = FALSE)
FibrocytesCounts <- RunTSNE(FibrocytesCounts, reduction = 'harmony', dims = 1:10)
TSNEPlot(FibrocytesCounts) + theme_bw() + xlab('t-SNE 1') + ylab('t-SNE 2')
```

```{r message=FALSE, warning=FALSE}
FibrocytesCounts <- FindNeighbors(FibrocytesCounts, reduction = 'harmony', verbose = FALSE)
FibrocytesCounts <- FindClusters(FibrocytesCounts, verbose = FALSE)
TSNEPlot(FibrocytesCounts, label = TRUE) + theme_bw() + xlab('t-SNE 1') + ylab('t-SNE 2') + theme(legend.position = 'None')
```


```{r fig.height=5, fig.width=10}
plot_density(object = FibrocytesCounts, 
             features = c('ACTA2','CD34', 'COL5A1', 'COL5A2', 'COL5A3', 'FAP'), 
             joint = FALSE)
```
```{r fig.height=5, fig.width=6}
P <- plot_density(object = FibrocytesCounts, 
                  features = c('ACTA2','CD34', 'COL5A1', 'COL5A2', 'COL5A3', 'FAP'), 
                  joint = TRUE)
P[[7]] + theme_bw() + xlab('t-SNE 1') + ylab('t-SNE 2') + theme(legend.position = 'None')
```

```{r}
DotPlot(object = FibrocytesCounts, scale.by = 'radius', scale = TRUE, dot.min = 0.4, 
        features = c('ACTA2','CD34', 'COL5A1', 'COL5A2', 'COL5A3', 'FAP')) + 
  coord_flip()
```
```{r}
table(Idents(FibrocytesCounts))
```
```{r message=TRUE, warning=FALSE, results= FALSE}
deFibrocytes <- FindMarkers(object = FibrocytesCounts, ident.1 = 8, test.use = 'MAST', verbose = FALSE)
```

```{r message=FALSE, warning=FALSE}
deFibrocytes$g <- rownames(deFibrocytes)
deFibrocytes$g[abs(deFibrocytes$avg_log2FC) < 1] <- NA
deFibrocytes$F <- log2(deFibrocytes$pct.1/deFibrocytes$pct.2)
deFibrocytes$g[abs(deFibrocytes$F) < 1] <- NA
deFibrocytes$color <- 'black'
deFibrocytes$color[deFibrocytes$avg_log2FC > 1] <- 'red'
deFibrocytes$color[deFibrocytes$avg_log2FC < -1] <- 'blue'
ggplot(deFibrocytes, mapping = aes(avg_log2FC, -log10(p_val), label = g)) + 
  geom_point(color = deFibrocytes$color, alpha = 0.5) + 
  geom_text_repel() + 
  theme_bw() + xlab(log[2]~(Avg~Fold-change)) +
  ylab(-log[10]~(P-value))

```
```{r message=FALSE, warning=FALSE}
log2FC <- deFibrocytes$avg_log2FC
names(log2FC) <- rownames(deFibrocytes)
enrichmentFibrocytes <- fgseaMultilevel(BIOP, log2FC)
enrichmentFibrocytes <- enrichmentFibrocytes[enrichmentFibrocytes$padj < 0.05,]
enrichmentFibrocytes$leadingEdge <- unlist(lapply(enrichmentFibrocytes$leadingEdge, function(X){paste0(X, collapse = ';')}))
enrichmentFibrocytes[order(enrichmentFibrocytes$NES, decreasing = TRUE),]
```

```{r, warning=FALSE, results= FALSE}
sseBIOP <- gsva(as.matrix(FibrocytesCounts@assays$RNA@data), BIOP, method = 'ssgsea')
```
```{r}
cellType <- ifelse(FibrocytesCounts$seurat_clusters %in% 8, 'Fibrocytes', 'Fibroblasts')
esFibrocytes <- data.frame(ES = sseBIOP['Prostaglandin biosynthesis and regulation',], CT = cellType)
ggplot(esFibrocytes, aes(CT, ES)) + 
  geom_violin() + 
  geom_boxplot(width = 0.1) + 
  theme_bw() +
  xlab('Cell Type') +
  ylab('Enrichment Score') +
  labs(title = 'Prostaglandin biosynthesis and regulation', 
       subtitle = expr_t_nonparametric(esFibrocytes, CT, ES))
```
